"""updated freebies in seed file

Revision ID: 73f4ef43ed00
Revises: 7db35e22400e
Create Date: 2023-06-26 03:33:05.482714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73f4ef43ed00'
down_revision = '7db35e22400e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
