"""finished oldest_company class method

Revision ID: 85f062e901b0
Revises: c02b98b61be6
Create Date: 2023-06-26 06:05:17.771046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85f062e901b0'
down_revision = 'c02b98b61be6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
