"""finished relationships and added print_details instance method to Freebie class in models

Revision ID: c02b98b61be6
Revises: 73f4ef43ed00
Create Date: 2023-06-26 05:16:14.089370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c02b98b61be6'
down_revision = '73f4ef43ed00'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
