"""finished give_freebie method

Revision ID: fab7a2aa58e1
Revises: 85f062e901b0
Create Date: 2023-06-26 06:26:57.454988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fab7a2aa58e1'
down_revision = '85f062e901b0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
