"""finished received_one method

Revision ID: fe52cca555f4
Revises: fab7a2aa58e1
Create Date: 2023-06-26 06:42:30.301719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe52cca555f4'
down_revision = 'fab7a2aa58e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
